## Task 1: A list of dictionaries

In [1]:
transactions = [
    {"id": 1, "product": "Laptop", "price": 1200, "quantity": 2, "region": "EU"},
    {"id": 2, "product": "Phone", "price": 800, "quantity": -1, "region": "US"},
    {"id": 3, "product": "Tablet", "price": 0, "quantity": 5, "region": "EU"},
    {"id": 4, "product": "Monitor", "price": 350, "quantity": 3, "region": "US"},
    {"id": 5, "product": "Laptop", "price": 1200, "quantity": 1, "region": "EU"},
    {"id": 6, "product": "Keyboard", "price": 75, "quantity": 10, "region": "APAC"},
]

# a) Filter valid transactions
valid_transactions = [
    t for t in transactions if t["price"] > 0 and t["quantity"] >= 0
]

# b) Add total field
for t in valid_transactions:
    t["total"] = t["price"] * t["quantity"]

# c) Group by region
region_totals = {}
for t in valid_transactions:
    region = t["region"]
    region_totals[region] = region_totals.get(region, 0) + t["total"]

# d) Find max region
max_region = max(region_totals, key=region_totals.get)
print(f"Highest revenue region: {max_region} with {region_totals[max_region]}")

Highest revenue region: EU with 3600


## Task 2: Creating a function

In [2]:
sales = [1200, 980, 1540, 870, 2010, 1650, 1300, 1100, 950, 1780, 2200, 1430, 1600, 1900]

def summarise_sales(sales):
    total = sum(sales)
    avg = round(total / len(sales), 2)
    best_day = sales.index(max(sales)) + 1
    worst_day = sales.index(min(sales)) + 1
    above_avg = sum(1 for s in sales if s > avg)

    return {
        "total": total,
        "average": avg,
        "best_day": best_day,
        "worst_day": worst_day,
        "above_average_count": above_avg
    }

print(summarise_sales(sales))

{'total': 20510, 'average': 1465.0, 'best_day': 11, 'worst_day': 4, 'above_average_count': 7}


## Task 3: Loops

In [3]:
students = [
    {"name": "Anna", "grade": 85, "attendance": 0.92},
    {"name": "Erik", "grade": 58, "attendance": 0.75},
    {"name": "Mia", "grade": 91, "attendance": 0.98},
    {"name": "Leo", "grade": 44, "attendance": 0.60},
    {"name": "Sara", "grade": 72, "attendance": 0.88},
    {"name": "Tom", "grade": 67, "attendance": 0.70},
    {"name": "Nina", "grade": 95, "attendance": 0.99},
    {"name": "Olli", "grade": 50, "attendance": 0.65},
]

# a)
passing = [s["name"] for s in students if s["grade"] >= 50]
print(passing)

# b)
for s in students:
    if s["grade"] >= 80:
        print(f"{s['name']}: Excellent")
    elif s["grade"] >= 50:
        print(f"{s['name']}: Pass")
    else:
        print(f"{s['name']}: Fail")

# c)
low_attendance = sum(1 for s in students if s["attendance"] < 0.80)
print(low_attendance)

# d)
top_student = students[0]
for s in students:
    if s["grade"] > top_student["grade"]:
        top_student = s
print(top_student["name"], top_student["grade"])

# e)
top = max(students, key=lambda x: x["grade"])
print(top["name"], top["grade"])

['Anna', 'Erik', 'Mia', 'Sara', 'Tom', 'Nina', 'Olli']
Anna: Excellent
Erik: Pass
Mia: Excellent
Leo: Fail
Sara: Pass
Tom: Pass
Nina: Excellent
Olli: Pass
4
Nina 95
Nina 95


## Task 4: Class and methods

In [4]:
class Portfolio:
    def __init__(self, owner):
        self.owner = owner
        self.holdings = {}

    def add_asset(self, ticker, shares, price):
        if ticker in self.holdings:
            self.holdings[ticker]["shares"] += shares
            self.holdings[ticker]["price_per_share"] = price
        else:
            self.holdings[ticker] = {"shares": shares, "price_per_share": price}

    def total_value(self):
        return sum(v["shares"] * v["price_per_share"] for v in self.holdings.values())

    def most_valuable(self):
        return max(self.holdings, key=lambda k: self.holdings[k]["shares"] * self.holdings[k]["price_per_share"])

    def __str__(self):
        return f"Portfolio of {self.owner}, Assets: {len(self.holdings)}, Total value: {self.total_value()}"

# Demo
p = Portfolio("Emilia")
p.add_asset("AAPL", 10, 150)
p.add_asset("TSLA", 5, 700)
p.add_asset("MSFT", 8, 300)

print(p)
print("Most valuable:", p.most_valuable())

Portfolio of Emilia, Assets: 3, Total value: 7400
Most valuable: TSLA


## Task 5: Datetime

In [5]:
from datetime import datetime

orders = [
    ("2025-01-15", "Laptop"), ("2025-01-22", "Phone"),
    ("2025-02-03", "Laptop"), ("2025-02-14", "Tablet"),
    ("2025-03-01", "Phone"), ("2025-03-10", "Phone"),
    ("2025-03-22", "Laptop"), ("2025-04-05", "Monitor"),
]

dates = [datetime.strptime(d, "%Y-%m-%d").date() for d, _ in orders]

print((max(dates) - min(dates)).days)

80


## Task 6: NumPy

In [6]:
import numpy as np

revenue = np.array([
    [210, 230, 190, 250],
    [220, 260, 200, 270],
    [250, 290, 230, 310]
])

# a)
print(revenue.sum(axis=1))

# b)
print(revenue.mean(axis=0))

# c)
growth = np.array([1.05, 1.03, 1.08, 1.02])
print(revenue[2] * growth)

# d)
print(revenue[revenue > 250])

[ 880  950 1080]
[226.66666667 260.         206.66666667 276.66666667]
[262.5 298.7 248.4 316.2]
[260 270 290 310]


## Task 7: Pandas

In [7]:
import pandas as pd

data = {
    "employee": ["Anna", "Erik", "Mia", "Leo", "Sara", "Tom"],
    "department": ["Finance", "Marketing", "Finance", "IT", "Marketing", "IT"],
    "salary": [4500, 4000, 4800, 5200, 3900, 5100],
    "years_exp": [5, 3, 7, 10, 2, 8],
    "performance_score": [4.2, 3.8, 4.5, 4.0, 3.5, 4.9]
}

df = pd.DataFrame(data)

# a)
df["salary_per_year_exp"] = (df["salary"] / df["years_exp"]).round()

# b)
print(df.sort_values("performance_score", ascending=False).head(3))

# c)
print(df.loc[(df["department"] == "Finance") & (df["performance_score"] > 4.0)])

# d)
df = df.rename(columns={"years_exp": "experience_years"})

# e)
print(df.iloc[:4][["salary", "performance_score"]])

  employee department  salary  years_exp  performance_score  \
5      Tom         IT    5100          8                4.9   
2      Mia    Finance    4800          7                4.5   
0     Anna    Finance    4500          5                4.2   

   salary_per_year_exp  
5                638.0  
2                686.0  
0                900.0  
  employee department  salary  years_exp  performance_score  \
0     Anna    Finance    4500          5                4.2   
2      Mia    Finance    4800          7                4.5   

   salary_per_year_exp  
0                900.0  
2                686.0  
   salary  performance_score
0    4500                4.2
1    4000                3.8
2    4800                4.5
3    5200                4.0


## Task 8: More Pandas

In [8]:
rng = np.random.default_rng(seed=123)
days = pd.date_range(start="2025-01-06", periods=28, freq="D")
visitors = rng.integers(200, 600, size=28)
conversion_rate = rng.uniform(0.02, 0.08, size=28).round(4)
avg_order_value = rng.normal(50, 10, size=28).round(2)

df = pd.DataFrame({
    "visitors": visitors,
    "conversion_rate": conversion_rate,
    "avg_order_value": avg_order_value
}, index=days)

df["conversions"] = (df["visitors"] * df["conversion_rate"]).round()
df["daily_revenue"] = df["conversions"] * df["avg_order_value"]

print(df.head())

            visitors  conversion_rate  avg_order_value  conversions  \
2025-01-06       206           0.0645            64.30         13.0   
2025-01-07       472           0.0578            48.44         27.0   
2025-01-08       437           0.0756            43.26         33.0   
2025-01-09       221           0.0339            43.61          7.0   
2025-01-10       563           0.0679            49.39         38.0   

            daily_revenue  
2025-01-06         835.90  
2025-01-07        1307.88  
2025-01-08        1427.58  
2025-01-09         305.27  
2025-01-10        1876.82  
